jobs:
  include:
    - stage: conditional_build
      notifications:
        email:
          on_success: [change]
          on_failure: [change]
      language: node_js
      node_js:
        - node
      install:
        - yarn install
      script:
        - test $TRAVIS_BRANCH != master && (test $TRAVIS_EVENT_TYPE = push || test $TRAVIS_EVENT_TYPE = pull_request) \
          && echo -e "\e[95mNot a CRON triggered build, thus only checking for errors." 
        - yarn lint --fix
        - yarn extractor
        - yarn builder
        - test $TRAVIS_EVENT_TYPE = cron \
          && echo -e "\e[95mCRON triggered build, thus building website." \
          && rm -rf docs \
          && yarn build \
          && touch docs/.nojekyll \
          && chmod +x .travis/write_cname.sh \
          && cd docs/ && ./../.travis/write_cname.sh \
          && cd ../ 
      after_success:
        - test $TRAVIS_EVENT_TYPE = cron \
          && echo -e "\e[95mDeploying to Repository" \
          && chmod +x .travis/push.sh \
          && ./.travis/push.sh
      cache:
        directories:
          - node_modules
