os: osx
language: node_js
cache:
  directories:
    - node_modules
node_js:
- node
script:
- npm run builder
- npm run extractor
- rm -rf docs
- npm run build
- touch docs/.nojekyll
after_success:
- chmod +x .travis/push.sh
- .travis/push.sh
